// <auto-generated />
namespace VirtoCommerce.CatalogPublishingModule.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ReadinessEntryAuditable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ReadinessEntryAuditable));
        
        string IMigrationMetadata.Id
        {
            get { return "201705120033537_ReadinessEntryAuditable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
